### ISSUE TITLE
DRAM access

### ISSUE THREAD

**Issue by IronySuzumiya** [IronySuzumiya/NiuDianNao#4]
Since the DRAM Databus Bitwidth is set to 64 bytes, we should separate a large DRAM request into several, and send them to DRAM one by one. But the whole process seems to be so slow, I wonder if it's appropriate or not. If we ‘correctly’ implement DRAM access in this way, it will take 6000+ cycles to load 32768 bytes of data from DRAM to SB, which is for only 1 turn (1 CP inst). Thus DRAM access will dominate the whole process of this system and that seems horrible.

**Comment by MemMeta** [comment]
You are correct. The latency for 32KB is reasonable.
